### ISSUE TITLE
TimeoutError: waiting for function failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by apopiidoru** [JonnyBurger/remotion#214]
First of all I want to congratulate you for this project, it's really awesome!

I have a small issue when I try to render my video, I get this error from Puppeteer: TimeoutError: waiting for function failed: timeout 30000ms exceeded.

I usually get this when I have a video file in the background, what can be done?

**Comment by JonnyBurger** [comment]
Hey @apopiidoru,

this happens when a `delayRender` call is being made and never being cleared - this means Remotion will wait forever until it marks itself as ready to render.

Can you copy a snippet how you include your video, I'll gladly help you out.

**Comment by apopiidoru** [comment]
Hi @JonnyBurger 

It's a little bit more complicated, but I'll simplify it to exemplify: 

`**Video.tsx**

import {Composition} from 'remotion';
import {MainScene} from './MainScene';

const fps = 30;
const videoConfig = {
  width: 1920,
  height: 1080,
	duration: Math.round(52 * fps) // nr of seconds * fps
};

export const RemotionVideo: React.FC = () => {
  return (
	<>
		<Composition
			id="MainScene"
			component={MainScene}
			durationInFrames={videoConfig.duration}
			fps={fps}
			width={videoConfig.width}
			height={videoConfig.height}
		/>
	</>
  );
};


**MainScene.tsx**

import {Sequence, useVideoConfig} from 'remotion';

import {LineByLine} from './Braun/LineByLine';
import {BackgroundVideo} from './Braun/BackgroundVideo';

// assets
import bullet_1 from './assets/bullet_01.svg';
import videoSrc from './assets/how-to-use-shaver-missing-animation-clean-2.mp4';

export const MainScene: React.FC = () => {
	const { durationInFrames } = useVideoConfig();

	return (
		<>
			<Sequence
				from={0}
				durationInFrames={durationInFrames}
			>
				<BackgroundVideo
					videoSrc={videoSrc || ''}
					width={1920}
					height={1080}
        />
			</Sequence>
			<Sequence
				from={68}
				durationInFrames={79}
			>
				<LineByLine
					text='Learn more about us'
					color="#FFFFFF"
					topPos={358}
					leftPos={243}
					iconSrc={bullet_1}
        />
			</Sequence>
		</>
	);
};
`

**Comment by apopiidoru** [comment]
And this is the output:
```
apopiidumitru@Apopiis-MacBook-Pro video-editor % npm run build

> remotion-template@1.0.0 build
> remotion render src/index.tsx MainScene out.mp4

Applied configuration from remotion.config.ts.
📦 (1/3) Bundling video...
📼 (2/3) Rendering frames (16x concurrency)...
[█████████████████████░░░░░░░░░░░░░░░░░░░] 51% | ETA: 43s | 801/1560TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/apopiidumitru/projects/video-editor/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForFunction (/Users/apopiidumitru/projects/video-editor/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:464:26)
    at Frame.waitForFunction (/Users/apopiidumitru/projects/video-editor/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:909:32)
    at Page.waitForFunction (/Users/apopiidumitru/projects/video-editor/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1286:33)
    at Object.provideScreenshot (/Users/apopiidumitru/projects/video-editor/node_modules/@remotion/renderer/dist/index.js:61:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/apopiidumitru/projects/video-editor/node_modules/@remotion/renderer/dist/render.js:49:9
    at async Promise.all (index 333)
    at async Object.renderFrames (/Users/apopiidumitru/projects/video-editor/node_modules/@remotion/renderer/dist/render.js:43:5)
npm ERR! code 1
npm ERR! path /Users/apopiidumitru/projects/video-editor
npm ERR! command failed
npm ERR! command sh -c remotion render src/index.tsx MainScene out.mp4

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apopiidumitru/.npm/_logs/2021-03-29T13_38_30_454Z-debug.log
```

**Comment by JonnyBurger** [comment]
Thanks for the repro!

Can you test the following for me?

- Does decreasing the concurrency work better? `npm run build -- --concurrency=2`

And can you tell me, does it always happen at frame 333? (you can tell from `at async Promise.all (index 333)`)

**Comment by apopiidoru** [comment]
I've done two tests with concurrency at 2 and it still happens :( they failed at:
1. ` at async Promise.all (index 1277)`
2. `at async Promise.all (index 1377)`

**Comment by JonnyBurger** [comment]
I see! I think Webpack might have trouble loading larger MP4 files correctly. 
I have noticed it myself this weekend and will initiate a fix soon.

A workaround for the moment is to `cd assets && npx serve` it.

Afterwards, instead of importing the video, pass src="http://localhost:5000/dev-video.mp4".

Can you tell me if this works? Would help me include a fix in a future version of Remotion 🙂

**Comment by apopiidoru** [comment]
I've done as you've requested and here's the error:

```
ERROR in external "http://localhost:5000/dev-video.mp4"
The target environment doesn't support EcmaScriptModule syntax so it's not possible to use external type 'module'
Error: The target environment doesn't support EcmaScriptModule syntax so it's not possible to use external type 'module'
```

**Comment by JonnyBurger** [comment]
@apopiidoru I meant not importing the video with an `import` statement, just passing the URL as the `src` and not importing anything.

Might have to verify with `yarn start` if it still works in the player too.

**Comment by apopiidoru** [comment]
I've just realized that too 🤦

**Comment by apopiidoru** [comment]
The workaround works as a charm! Thank you very much @JonnyBurger!

**Comment by JonnyBurger** [comment]
Awesome! 
But on the other hand a real bug I also just noticed yesterday. Related to #210, I'll make sure that in a future release this is better handled!

**Comment by JonnyBurger** [comment]
@apopiidoru You are right, that was only my initial suspicion but there are problems occurring with much lower file sizes as well. The bottleneck seems to be `file-loader`, I'm trying to come up with a solution for it soon.

For now I corrected the issue description.

**Comment by natasha-93** [comment]
We're also experiencing this same error `TimeoutError: waiting for function failed: timeout 30000ms exceeded` but we're not importing any files. We're also not using the delayRender() function.

**Comment by JonnyBurger** [comment]
@natasha-93 Please first see this document for possible reasons: https://www.remotion.dev/docs/timeout/

If you are not using a delayRender(), are you possibly rendering a `<Video />` with an unsupported codec? These articles could be helpful: https://www.remotion.dev/docs/media-playback-error https://www.remotion.dev/docs/non-seekable-media

If it's none of these, I need some more information about the markup that you are rendering and that is causing a timeout.

**Comment by natasha-93** [comment]
Ok, changing parallelism to a set number instead of the default worked for now. Thanks!

**Comment by iamkhalidbashir** [comment]
`TimeoutError: waiting for function failed: timeout 30000ms` with parallelism greater than 1 randomly

**Comment by iamkhalidbashir** [comment]
> You are right, that was only my initial suspicion but there are problems occurring with much lower file sizes as well. The bottleneck seems to be `file-loader`, I'm trying to come up with a solution for it soon.
> 
> For now I corrected the issue description.

Should we open this issue then?

**Comment by JonnyBurger** [comment]
@iamkhalidbashir Sorry for the slow response - 

I thought to have fixed the webpack bottleneck with our own fork of webpack-dev-middleware. So if you get a timeout it's probably something else. Did you go through https://remotion.dev/docs/timeout for possible reasons?

**Comment by idkblogs** [comment]
I am getting the same errors on emotion while `npm run build`, Plz help me to solve this.


An error occurred:
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\browser\DOMWorld.js:156:34)
    at DOMWorld.waitForFunction (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\browser\DOMWorld.js:106:26)
    at waitForReady (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\seek-to-frame.js:21:25)
    at seekToFrame (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\seek-to-frame.js:52:36)
    at renderFrameWithOptionToReject (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\render-frames.js:166:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    
    
    
    It is happening when I add a long video, I tried the above-provided workaround for the moment ie. `cd assets && npx serve` but it is still not working.
    
    
    
    Here are some pieces of my codes:
    
   ```
 
    import {AbsoluteFill, OffthreadVideo, staticFile} from 'remotion';
import {
	VIDEO_RESOLTION_WIDTH,
	VIDEO_RESOLTION_HEIGHT,
} from '../../constants/constant';

export const VideoWithText: React.FC<{
	link: any;
	delay: number;
	startFrom?: number;
	endAt?: number;
	videoSpeed?: number;
	isMuted?: boolean;
	opacity?: number;
	loop?: false;
	videoObject: any;
}> = ({
	videoObject,
	delay,
	link,
	startFrom,
	endAt,
	videoSpeed,
	isMuted = true,
	opacity = 1,
	loop,
}) => {
	const {
		videoWidth = VIDEO_RESOLTION_WIDTH,
		videoHeight = VIDEO_RESOLTION_HEIGHT,
		marginTop = '0px',
		marginLeft = '0px',
		videoBorderWidth,
		videoBorderColor,
		videoRadius,
		volume,
	} = videoObject;
	// const loacFileUrl = staticFile(link);
	const loacFileUrl = link;

	return (
		<AbsoluteFill>
			<OffthreadVideo
				src={loacFileUrl}
				style={{
					opacity,
					width: videoWidth,
					height: videoHeight,
					padding: '0px',
					marginLeft: marginLeft,
					marginTop: marginTop,
					border: `${videoBorderWidth} solid ${videoBorderColor}`,
					borderRadius: videoRadius,
				}}
				startFrom={startFrom}
				endAt={endAt}
				playbackRate={videoSpeed}
				muted={isMuted}
				volume={volume}
			/>
		</AbsoluteFill>
	);
};

```
    


**Earlier I was using `delayRender()` but I tried to comment on that code, still I getting error:**

```

import {useEffect, useState} from 'react';
import {
	Composition,
	// continueRender,
	// delayRender,
	getInputProps,
} from 'remotion';
import {getDuration} from '../utils/fetch-msgs';
import {Story} from './Story';
import {
	FRAME_PER_SECOND,
	CONTENTS_LENGTH,
	VIDEO_RESOLTION_WIDTH,
	VIDEO_RESOLTION_HEIGHT,
	CONFIG_BLOG_CONTENTS,
} from '../constants/constant';

const {
	global: {TOTAL_VIDEO_DURATION_IN_FRAMES},
} = CONFIG_BLOG_CONTENTS;

export const RemotionVideo: React.FC = () => {
	const props = getInputProps();
	// const [handle] = useState(() => delayRender("Getting duration..."));
	const [duration, setDuration] = useState<number | null>(1000);
	const [apiResponse, setApiResponse] = useState<object | null>({});

	useEffect(
		() => {
			getDuration(CONTENTS_LENGTH).then(({entrance, response}) => {
				setDuration(Math.floor(entrance));
				setApiResponse(response);
				// continueRender(handle);
			});
		},
		[
			// handle
		]
	);


	return (
		<>
			<Composition
				id="Story"
				component={Story}
				durationInFrames={TOTAL_VIDEO_DURATION_IN_FRAMES}
				fps={FRAME_PER_SECOND}
				width={VIDEO_RESOLTION_WIDTH - 10}
				height={VIDEO_RESOLTION_HEIGHT - 10}
				defaultProps={{
					messageIds: '',
					apiResponse,
				}}
			/>
		</>
	);
};
```


**Now I am not using delayRender() in their codes and getting the error:**

```

(1/3) ╭───────────────────╮ Bundled code 2622ms
Entry point = src\index.tsx (argument passed - found in cwd), Composition = Story (Passed as argument), Codec = h264 (derived from out name), Output = results/16Sept_StartCompany0924.mp4
(2/3)                       Rendering frames (6x) 0/3620
    + ╭───────────────────╮ Downloading 2 files                                                                      
(3/3)                       Encoding video 0/3620
Symbolicating minified error message...
A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mAn error occurred while rendering frame 0:ut not cleared after 28000ms. See https://remotion.dev/docs/timeout for hel
 Error  A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mp4&time=1.6&imageFormat=jpeg" was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help.

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:41
39 │         ]
40 │             .filter(truthy_js_1.truthy)
41 │             .join(' ');
42 │         throw new Error(message);
43 │     }, timeoutToUse);
44 │ }


🕧 The delayRender() call is located at:

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:27
25 │ const handle = Math.random();
26 │ handles.push(handle);
27 │ const called = (_b = (_a = Error().stack) === null || _a === void 0 ? void 0 : _a.replace(/^Error/g, '')) !== null && _b !== void 0 ? _b : '';
28 │ if ((0, get_environment_js_1.getRemotionEnvironment)() === 'rendering') {
29 │     const timeoutToUse = typeof window === 'undefined'
30 │         ? defaultTimeout

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/Img.js:62
60 │     return;
61 │ }
62 │ const newHandle = (0, delay_render_js_1.delayRender)('Loading <Img> with src=' + src);
63 │ const { current } = imageRef;
64 │ const onComplete = () => {
65 │     var _a, _b, _c, _d;
at Rj (node_modules/react-dom/cjs/react-dom.production.min.js:244)
at lk (node_modules/react-dom/cjs/react-dom.production.min.js:261)
at jk (node_modules/react-dom/cjs/react-dom.production.min.js:260)
at jk (node_modules/react-dom/cjs/react-dom.production.min.js:260)
at ik (node_modules/react-dom/cjs/react-dom.production.min.js:259)
at Xk (node_modules/react-dom/cjs/react-dom.production.min.js:283)
at Qk (node_modules/react-dom/cjs/react-dom.production.min.js:281)
at Hk (node_modules/react-dom/cjs/react-dom.production.min.js:270)
at (node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:42)

💡 Get help for this issue at https://remotion.dev/docs/timeout
```
 
    

**Please help**
