### ISSUE TITLE
Assets with relative URLs fail the build

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#277]
I have an Audio file referenced with a URL relative to the page location:

```
<Audio src="/audio-1-norm-19d6f70ev.mp3"/>
```

The src is coming from a custom WebPack loader. It works fine in the preview mode.

But when I try to build it, Remotion gives an error:

```
(node:28379) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /audio-1-norm-19d6f70ev.mp3
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at Object.downloadAndMapAssetsToFileUrl (/home/ubuntu/workspace/udemy_cloudfront_course/node_modules/@remotion/renderer/dist/assets/download-and-map-assets-to-file.js:48)
    at /home/ubuntu/workspace/udemy_cloudfront_course/node_modules/@remotion/renderer/dist/assets/convert-assets-to-file-urls.js:8:54
    at Array.map (<anonymous>)
    at /home/ubuntu/workspace/udemy_cloudfront_course/node_modules/@remotion/renderer/dist/assets/convert-assets-to-file-urls.js:7:43
    at Array.map (<anonymous>)
    at Object.convertAssetsToFileUrls (/home/ubuntu/workspace/udemy_cloudfront_course/node_modules/@remotion/renderer/dist/assets/convert-assets-to-file-urls.js:6:31)
    at stitchFramesToVideo (/home/ubuntu/workspace/udemy_cloudfront_course/node_modules/@remotion/renderer/dist/stitcher.js:82:63)
    at async /home/ubuntu/workspace/udemy_cloudfront_course/build.js:62:3
(Use `node --trace-warnings ...` to show where the warning was created)
```

I'm using remotion 2.0.2.

As a workaround I can prepend the url with ```window.location.origin```, as I've found that's the [check condition](https://github.com/JonnyBurger/remotion/blob/07e45a2ba99d23087a8a05e85edbd83185dfdd90/packages/core/src/is-remote-asset.ts#L1).

**Comment by JonnyBurger** [comment]
Hey Tamás! Thanks for the report, I'll look if there is something that can be done better.

What kind of Webpack Loader are you using? Why not the default one?

We can assume that if this case occurs that we prepend window.location.origin (`new URL(props.src, window.location.origin).href`), but I wanna check that nothing breaks and understand the issue a bit better.

**Comment by sashee** [comment]
I needed to run some normalization automatically for all imported audio files, but I since moved that to a different loader. Now it extracts the duration for the audio and returns it along with the file (it was before you added client-side support for audio duration).

If you are interested, this is the code for it (the interesting parts are the ```emitFile``` and the ```results```):

```
const loaderUtils = require("loader-utils");
const child_process = require("child_process");
const util = require("util");
const os = require("os");
const path = require("path");
const fs = require("fs").promises;

const ASSET_PATH = process.env.ASSET_PATH || "/";

const exec = util.promisify(child_process.exec);

const withTempDir = async (fn) => {
	const dir = await fs.mkdtemp(await fs.realpath(os.tmpdir()) + path.sep);
	try {
		return await fn(dir);
	}finally {
		fs.rmdir(dir, {recursive: true});
	}
};

module.exports = function (source) {
	const callback = this.async();
	(async () => {
		const file = source;
		return withTempDir(async (dir) => {
			const fileName = path.join(dir, "input");

			await fs.writeFile(fileName, source);

			const ffmpegCommand = `ffmpeg -i ${fileName} -v quiet -stats -f null -`;
			const {stderr: durationString} = await exec(ffmpegCommand);
			const {hours, minutes, seconds, mss} = durationString.trim().match(/time=(?<hours>\d+):(?<minutes>\d+):(?<seconds>\d+)\.(?<mss>\d+)\s[^\r]*$/).groups;
			const inSeconds = parseInt(hours, 10) * 60 * 60 + parseInt(minutes, 10) * 60 + parseInt(seconds, 10) + parseInt(mss, 10) / 1000;

			const {stdout: formatString} = await exec(`ffprobe -v quiet -print_format json -show_format ${fileName}`);
			const formatName = JSON.parse(formatString).format.format_name;

			const filename = loaderUtils.interpolateName(this, `[name]-[contenthash].${formatName}`, {content: file});

			this.emitFile(filename, file);

			const results = {
				file: `${ASSET_PATH}${filename}`,
				duration: inSeconds,
			};

			return `export default ${JSON.stringify(results)}`;
		});
	})().then((res) => callback(undefined, res), (err) => callback(err));
};
module.exports.raw = true;
```

When I use it in a file:

```
import audio1 from "./audio/js-audio-1.mp3";
```

It emits a file and returns an object with ```file``` and ```duration```:

```
{file: "/1-7706a8597c5fa85d7951756bdc77d306.wav", duration: 14.049}
```

The ```file-loader``` (the "default one") outputs absolute URLs and mine returns relative ones. The ```file-loader``` does some webpack magic to get the current host that I couldn't figure out, but a relative URL should work too.

**Comment by JonnyBurger** [comment]
OK, I see no harm in doing it! Thanks for the report!
Will release 2.0.4 tonight, please report back if it doesn't solve the issue!
