### ISSUE TITLE
Sequence API for Audio fails when durationInFrames is non-integer

### ISSUE THREAD

**Issue by ieric2** [JonnyBurger/remotion#280]
Non-integer durationInFrames works when wrapping all other components besides {Audio}

Error below:

```
bundle.js:31062 Uncaught RangeError: Invalid array length
    at bundle.js:31062
    at mountMemo (bundle.js:16736)
    at Object.useMemo (bundle.js:17022)
    at Object.useMemo (bundle.js:27896)
    at Object.useMediaInTimeline (bundle.js:31058)
    at AudioForDevelopment (bundle.js:29080)
    at renderWithHooks (bundle.js:16149)
    at mountIndeterminateComponent (bundle.js:18269)
    at beginWork (bundle.js:19056)
    at HTMLUnknownElement.callCallback2 (bundle.js:8746)
    at Object.invokeGuardedCallbackDev (bundle.js:8771)
    at invokeGuardedCallback (bundle.js:8805)
    at beginWork$1 (bundle.js:22163)
    at performUnitOfWork (bundle.js:21391)
    at workLoopSync (bundle.js:21345)
    at renderRootSync (bundle.js:21320)
    at performSyncWorkOnRoot (bundle.js:21060)
    at bundle.js:13596
    at unstable_runWithPriority (bundle.js:32396)
    at runWithPriority$1 (bundle.js:13556)
    at flushSyncCallbackQueueImpl (bundle.js:13592)
    at flushSyncCallbackQueue (bundle.js:13582)
    at scheduleUpdateOnFiber (bundle.js:20834)
    at dispatchAction (bundle.js:16947)
    at ResizeObserver.<anonymous> (bundle.js:2094)
(anonymous) @ bundle.js:31062
mountMemo @ bundle.js:16736
useMemo @ bundle.js:17022
useMemo @ bundle.js:27896
useMediaInTimeline @ bundle.js:31058
AudioForDevelopment @ bundle.js:29080
renderWithHooks @ bundle.js:16149
mountIndeterminateComponent @ bundle.js:18269
beginWork @ bundle.js:19056
callCallback2 @ bundle.js:8746
invokeGuardedCallbackDev @ bundle.js:8771
invokeGuardedCallback @ bundle.js:8805
beginWork$1 @ bundle.js:22163
performUnitOfWork @ bundle.js:21391
workLoopSync @ bundle.js:21345
renderRootSync @ bundle.js:21320
performSyncWorkOnRoot @ bundle.js:21060
(anonymous) @ bundle.js:13596
unstable_runWithPriority @ bundle.js:32396
runWithPriority$1 @ bundle.js:13556
flushSyncCallbackQueueImpl @ bundle.js:13592
flushSyncCallbackQueue @ bundle.js:13582
scheduleUpdateOnFiber @ bundle.js:20834
dispatchAction @ bundle.js:16947
(anonymous) @ bundle.js:2094
bundle.js:24932 The above error occurred in the <AudioForDevelopment> component:

    at AudioForDevelopment (http://localhost:3000/bundle.js:29070:28)
    at Audio (http://localhost:3000/bundle.js:29019:10)
    at div
    at Sequence (http://localhost:3000/bundle.js:30758:20)
    at div
    at div
    at div
    at GenerativeVideo (http://localhost:3000/bundle.js:102:3)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at div
    at Suspense
    at Inner (http://localhost:3000/bundle.js:1871:17)
    at VideoPreview (http://localhost:3000/bundle.js:1910:24)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at Canvas (http://localhost:3000/bundle.js:1341:23)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at div
    at SplitterElement (http://localhost:3000/bundle.js:2182:27)
    at div
    at SplitterContainer (http://localhost:3000/bundle.js:2086:29)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at TopPanel
    at div
    at SplitterElement (http://localhost:3000/bundle.js:2182:27)
    at div
    at SplitterContainer (http://localhost:3000/bundle.js:2086:29)
    at div
    at styled.div (http://localhost:3000/bundle.js:33100:6)
    at Editor (http://localhost:3000/bundle.js:1584:35)
    at RemotionRoot (http://localhost:3000/bundle.js:28856:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by JonnyBurger** [comment]
Thanks, good catch!
Non-integer durations for sequences should throw an error, just like in compositions.
I'll fix this shortly.
