### ISSUE TITLE
Cannot render mp4. ffmpeg breaks when containerized

### ISSUE THREAD

**Issue by abdielou** [JonnyBurger/remotion#425]
Hi

I have a custom Docker container and server. Long story short, jpeg frames are generated correctly but `ffmpeg` breaks. If I run the same `ffmpeg` command directly in the container's console, the video is generated with no issues.

```
 Rendering frames...
 Rendered frame 10
 Rendered frame 20
 Rendered frame 30
 Rendered frame 40
 Rendered frame 50
 Rendered frame 60
 Rendered frame 70
 Rendered frame 80
 Rendered frame 90
 Rendered frame 100
 Rendered frame 110
 Rendered frame 120
 Rendered frame 130
 Rendered frame 140
 Rendered frame 150
 error: Error: Command was killed with SIGKILL (Forced termination): ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4
 ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers
   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
   configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
   libavutil      55. 34.101 / 55. 34.101
   libavcodec     57. 64.101 / 57. 64.101
   libavformat    57. 56.101 / 57. 56.101
   libavdevice    57.  1.100 / 57.  1.100
   libavfilter     6. 65.100 /  6. 65.100
   libavresample   3.  1.  0 /  3.  1.  0
   libswscale      4.  2.100 /  4.  2.100
   libswresample   2.  3.100 /  2.  3.100
   libpostproc    54.  1.100 / 54.  1.100
 Input #0, image2, from 'element-%03d.jpeg':
   Duration: 00:00:05.00, start: 0.000000, bitrate: N/A
     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 30 tbn, 30 tbc
 [swscaler @ 0x563cff322340] deprecated pixel format used, make sure you did set range correctly
 [libx264 @ 0x563cfee11d20] using SAR=1/1
 [libx264 @ 0x563cfee11d20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
 [libx264 @ 0x563cfee11d20] profile High, level 4.0
 [libx264 @ 0x563cfee11d20] 264 - core 148 r2748 97eaef2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
 Output #0, mp4, to '/tmp/remotion-1cTrTI/out.mp4':
   Metadata:
     encoder         : Lavf57.56.101
     Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 1000 kb/s, 30 fps, 15360 tbn, 30 tbc
     Metadata:
       encoder         : Lavc57.64.101 libx264
     Side data:
       cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: -1
 Stream mapping:
   Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
 Press [q] to stop, [?] for help
frame=   63 fps= 59 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    te=N/A speed=   0x
     at makeError (/opt/app/node_modules/execa/lib/error.js:59:11)
     at handlePromise (/opt/app/node_modules/execa/index.js:114:26)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:94:5)
     at async stitchFramesToVideo (/opt/app/node_modules/@remotion/renderer/dist/stitcher.js:133:5)
     at async run (/opt/app/app/controllers/animations/build-animation.js:56:7)
 error: task - build-animation - error occured: {"shortMessage":"Command was killed with SIGKILL (Forced termination): ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4","command":"ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4","signal":"SIGKILL","signalDescription":"Forced termination","stdout":"","stderr":"ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516\n  configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 34.101 / 55. 34.101\n  libavcodec     57. 64.101 / 57. 64.101\n  libavformat    57. 56.101 / 57. 56.101\n  libavdevice    57.  1.100 / 57.  1.100\n  libavfilter     6. 65.100 /  6. 65.100\n  libavresample   3.  1.  0 /  3.  1.  0\n  libswscale      4.  2.100 /  4.  2.100\n  libswresample   2.  3.100 /  2.  3.100\n  libpostproc    54.  1.100 / 54.  1.100\nInput #0, image2, from 'element-%03d.jpeg':\n  Duration: 00:00:05.00, start: 0.000000, bitrate: N/A\n    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 30 tbn, 30 tbc\n[swscaler @ 0x563cff322340] deprecated pixel format used, make sure you did set range correctly\n[libx264 @ 0x563cfee11d20] using SAR=1/1\n[libx264 @ 0x563cfee11d20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2\n[libx264 @ 0x563cfee11d20] profile High, level 4.0\n[libx264 @ 0x563cfee11d20] 264 - core 148 r2748 97eaef2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\nOutput #0, mp4, to '/tmp/remotion-1cTrTI/out.mp4':\n  Metadata:\n    encoder         : Lavf57.56.101\n    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 1000 kb/s, 30 fps, 15360 tbn, 30 tbc\n    Metadata:\n      encoder         : Lavc57.64.101 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: -1\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\nframe=   49 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \rframe=   63 fps= 59 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    ","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
 error: Error: Command was killed with SIGKILL (Forced termination): ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4
 ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers
   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
   configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
   libavutil      55. 34.101 / 55. 34.101
   libavcodec     57. 64.101 / 57. 64.101
   libavformat    57. 56.101 / 57. 56.101
   libavdevice    57.  1.100 / 57.  1.100
   libavfilter     6. 65.100 /  6. 65.100
   libavresample   3.  1.  0 /  3.  1.  0
   libswscale      4.  2.100 /  4.  2.100
   libswresample   2.  3.100 /  2.  3.100
   libpostproc    54.  1.100 / 54.  1.100
 Input #0, image2, from 'element-%03d.jpeg':
   Duration: 00:00:05.00, start: 0.000000, bitrate: N/A
     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 30 tbn, 30 tbc
 [swscaler @ 0x563cff322340] deprecated pixel format used, make sure you did set range correctly
 [libx264 @ 0x563cfee11d20] using SAR=1/1
 [libx264 @ 0x563cfee11d20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
 [libx264 @ 0x563cfee11d20] profile High, level 4.0
 [libx264 @ 0x563cfee11d20] 264 - core 148 r2748 97eaef2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
 Output #0, mp4, to '/tmp/remotion-1cTrTI/out.mp4':
   Metadata:
     encoder         : Lavf57.56.101
     Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 1000 kb/s, 30 fps, 15360 tbn, 30 tbc
     Metadata:
       encoder         : Lavc57.64.101 libx264
     Side data:
       cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: -1
 Stream mapping:
   Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
 Press [q] to stop, [?] for help
frame=   63 fps= 59 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    te=N/A speed=   0x
     at makeError (/opt/app/node_modules/execa/lib/error.js:59:11)
     at handlePromise (/opt/app/node_modules/execa/index.js:114:26)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:94:5)
     at async stitchFramesToVideo (/opt/app/node_modules/@remotion/renderer/dist/stitcher.js:133:5)
     at async run (/opt/app/app/controllers/animations/build-animation.js:56:7)
 error: task - build-animation - error occured: {"shortMessage":"Command was killed with SIGKILL (Forced termination): ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4","command":"ffmpeg -r 30 -f image2 -s 1920x1080 -start_number 0 -i element-%03d.jpeg -c:v libx264 -crf 18 -pix_fmt yuv420p -b:v 1M -c:a aac -map 0:v -y /tmp/remotion-1cTrTI/out.mp4","signal":"SIGKILL","signalDescription":"Forced termination","stdout":"","stderr":"ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516\n  configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 34.101 / 55. 34.101\n  libavcodec     57. 64.101 / 57. 64.101\n  libavformat    57. 56.101 / 57. 56.101\n  libavdevice    57.  1.100 / 57.  1.100\n  libavfilter     6. 65.100 /  6. 65.100\n  libavresample   3.  1.  0 /  3.  1.  0\n  libswscale      4.  2.100 /  4.  2.100\n  libswresample   2.  3.100 /  2.  3.100\n  libpostproc    54.  1.100 / 54.  1.100\nInput #0, image2, from 'element-%03d.jpeg':\n  Duration: 00:00:05.00, start: 0.000000, bitrate: N/A\n    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 30 tbn, 30 tbc\n[swscaler @ 0x563cff322340] deprecated pixel format used, make sure you did set range correctly\n[libx264 @ 0x563cfee11d20] using SAR=1/1\n[libx264 @ 0x563cfee11d20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2\n[libx264 @ 0x563cfee11d20] profile High, level 4.0\n[libx264 @ 0x563cfee11d20] 264 - core 148 r2748 97eaef2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\nOutput #0, mp4, to '/tmp/remotion-1cTrTI/out.mp4':\n  Metadata:\n    encoder         : Lavf57.56.101\n    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 1000 kb/s, 30 fps, 15360 tbn, 30 tbc\n    Metadata:\n      encoder         : Lavc57.64.101 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: -1\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\nframe=   49 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \rframe=   63 fps= 59 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    ","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
```

**Comment by JonnyBurger** [comment]
Hi Abdiel!

I suspect it is because the docker container is running out of memory. Are you running Docker Desktop by any chance? Then it is easy to increase the memory (https://docs.docker.com/docker-for-mac/). For other ways of running Docker I don't have a handy tutorial ready right now.

**Comment by abdielou** [comment]
@JonnyBurger I'll try increasing memory, but the command does runs fine if I execute it from command line inside the same containr.

**Comment by abdielou** [comment]
@JonnyBurger Seems like it's not a memory issue. I increased to 8 Gigs and still the same error. Also, the error is immediate.

**Comment by abdielou** [comment]
@JonnyBurger It was a memory issue. Thank you.

**Comment by JonnyBurger** [comment]
Ok, glad you figured it out! 🙌 
It makes sense that it works on the  normal CLI but not inside Docker, because Docker limits the memory, not necessarily to  the amount that is normally available on the system.
