### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/create-remotion: Not found"

### ISSUE THREAD

**Issue by osamasayed** [JonnyBurger/remotion#426]
When trying to install remotion through yarn, it shows this error, I am using MacOs Big Sur v11.4:

```
yarn create remotion                                                                                                                                   1456ms  Sat Jun  5 09:45:34 2021
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-remotion: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/macbook/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

And here are the logs inside yarn-error.log:

```
Arguments: 
  /usr/local/Cellar/node/16.0.0_1/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js create remotion

Yarn version: 
  1.22.10

Node version: 
  16.0.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/create-remotion: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
      at Request.emit (node:events:365:28)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
      at Request.emit (node:events:365:28)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (node:events:471:28)
      at IncomingMessage.emit (node:events:377:35)
      at endReadableNT (node:internal/streams/readable:1312:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm manifest: 
  {
    "dependencies": {
      "create-next-app": "^10.2.0",
      "create-nuxt-app": "^3.4.0",
      "create-react-app": "^4.0.3",
      "create-umi": "^0.26.0",
      "create-video": "^2.1.1"
    }
  }

yarn manifest: 
  No manifest
```

**Comment by JonnyBurger** [comment]
We hopefully never put this command in our documentation, it should be `yarn create video` :)

**Comment by osamasayed** [comment]
Oh my bad sorrrry :D

**Comment by JonnyBurger** [comment]
No prob! 👍
